# Add any block that signs are allowed to replace

replaceable-blocks:
  - ACACIA_SAPLING
  - ALLIUM
  - ATTACHED_MELON_STEM
  - ATTACHED_PUMPKIN_STEM
  - AZURE_BLUET
  - BIG_DRIPLEAF
  - BIRCH_SAPLING
  - BLUE_ORCHID
  - BROWN_MUSHROOM
  - BUSH
  - CARROTS
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - CHERRY_SAPLING
  - COBWEB
  - CORNFLOWER
  - DANDELION
  - DARK_OAK_SAPLING
  - DEAD_BUSH
  - FERN
  - GLOW_LICHEN
  - JUNGLE_SAPLING
  - KELP
  - KELP_PLANT
  - LARGE_FERN
  - LEAF_LITTER
  - LILAC
  - LILY_OF_THE_VALLEY
  - MANGROVE_PROPAGULE
  - MELON_STEM
  - MOSS_CARPET
  - NETHER_SPROUTS
  - OAK_SAPLING
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PEONY
  - PINK_PETALS
  - PINK_TULIP
  - PITCHER_PLANT
  - POPPY
  - POTATOES
  - PUMPKIN_STEM
  - RED_MUSHROOM
  - RED_TULIP
  - ROSE_BUSH
  - SEAGRASS
  - SHORT_DRY_GRASS
  - SHORT_GRASS
  - SMALL_DRIPLEAF
  - SNOW
  - SPRUCE_SAPLING
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TALL_DRY_GRASS
  - TALL_GRASS
  - TALL_SEAGRASS
  - TORCHFLOWER
  - TWISTING_VINES
  - VINE
  - WHEAT
  - WHITE_TULIP
  - WITHER_ROSE